#!/usr/bin/env bash
# Init script to manage manage_my_process

PIDFILE="/var/run/my_process.pid"

start() {
    if [ -f "$PIDFILE" ]; then
        echo "manage_my_process is already running."
        exit 1
    fi

    # Start the manage_my_process in the background
    ./manage_my_process &
    echo "$!" > "$PIDFILE"
    echo "manage_my_process started"
}

stop() {
    if [ ! -f "$PIDFILE" ]; then
        echo "manage_my_process is not running."
        exit 1
    fi

    kill -15 "$(cat "$PIDFILE")" && rm -f "$PIDFILE"
    echo "manage_my_process stopped"
}

restart() {
    stop
    start
    echo "manage_my_process restarted"
}

case "$1" in 
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
